import React, { useMemo } from 'react';
import Plot from 'react-plotly.js';

const matrixDet3x3 = (m) => {
  return m[0][0]*(m[1][1]*m[2][2] - m[1][2]*m[2][1]) -
         m[0][1]*(m[1][0]*m[2][2] - m[1][2]*m[2][0]) +
         m[0][2]*(m[1][0]*m[2][1] - m[1][1]*m[2][0]);
};

const solve3x3 = (A, B) => {
  const detA = matrixDet3x3(A);
  if (Math.abs(detA) < 1e-9) return null; // Parallel planes

  const detX = matrixDet3x3([[B[0], A[0][1], A[0][2]], [B[1], A[1][1], A[1][2]], [B[2], A[2][1], A[2][2]]]);
  const detY = matrixDet3x3([[A[0][0], B[0], A[0][2]], [A[1][0], B[1], A[1][2]], [A[2][0], B[2], A[2][2]]]);
  const detZ = matrixDet3x3([[A[0][0], A[0][1], B[0]], [A[1][0], A[1][1], B[1]], [A[2][0], A[2][1], B[2]]]);

  return [detX / detA, detY / detA, detZ / detA];
};

const FeasibleRegion3D = ({ constraints }) => {
  const vertices = useMemo(() => {
    if (!constraints || constraints.length === 0 || constraints[0].coeffs.length !== 3) return [];

    const planes = [
      // non-negativity constraints: x>=0, y>=0, z>=0
      { a: 1, b: 0, c: 0, d: 0, type: '>=' },
      { a: 0, b: 1, c: 0, d: 0, type: '>=' },
      { a: 0, b: 0, c: 1, d: 0, type: '>=' }
    ];

    constraints.forEach(c => {
      planes.push({ 
        a: c.coeffs[0], 
        b: c.coeffs[1], 
        c: c.coeffs[2], 
        d: c.rhs, 
        type: '<=' // default to canonical form
      });
    });

    const validVertices = [];

    // Brute force intersection of all triplets of planes
    for (let i = 0; i < planes.length; i++) {
      for (let j = i + 1; j < planes.length; j++) {
        for (let k = j + 1; k < planes.length; k++) {
          const A = [
            [planes[i].a, planes[i].b, planes[i].c],
            [planes[j].a, planes[j].b, planes[j].c],
            [planes[k].a, planes[k].b, planes[k].c]
          ];
          const B = [planes[i].d, planes[j].d, planes[k].d];
          
          const pt = solve3x3(A, B);
          if (pt) {
            // Check if pt satisfies ALL constraints
            let feasible = true;
            for (let p of planes) {
              const val = p.a * pt[0] + p.b * pt[1] + p.c * pt[2];
              if (p.type === '<=' && val > p.d + 1e-6) feasible = false;
              if (p.type === '>=' && val < p.d - 1e-6) feasible = false;
            }
            if (feasible) {
              // Add only unique vertices
              const isDuplicate = validVertices.some(v => 
                Math.abs(v[0]-pt[0]) < 1e-5 && Math.abs(v[1]-pt[1]) < 1e-5 && Math.abs(v[2]-pt[2]) < 1e-5
              );
              if (!isDuplicate) validVertices.push(pt);
            }
          }
        }
      }
    }
    return validVertices;
  }, [constraints]);

  if (!vertices || vertices.length < 4) {
    return (
      <div className="card p-6 mt-6 shadow-sm border-dashed border-gray-300 dark:border-slate-600 bg-gray-50/50 dark:bg-slate-800/50 text-center">
        <h3 className="font-bold text-lg mb-2 text-gray-600 dark:text-gray-400">3D Plot Unavailable</h3>
        <p className="text-sm text-gray-500">
          The feasible region is unbounded or has no valid 3D intersections, so a polyhedron cannot be rendered.
        </p>
      </div>
    );
  }

  const x = vertices.map(v => v[0]);
  const y = vertices.map(v => v[1]);
  const z = vertices.map(v => v[2]);

  return (
    <div className="card p-6 mt-6 shadow-sm overflow-hidden">
      <h3 className="font-bold text-lg mb-4 text-gray-800 dark:text-gray-200">3D Feasible Region Preview</h3>
      <div className="w-full flex justify-center bg-gray-50 dark:bg-slate-800/50 rounded-lg">
        <Plot
          data={[
            {
              type: 'mesh3d',
              x: x,
              y: y,
              z: z,
              opacity: 0.5,
              color: 'rgba(59, 130, 246, 0.6)',
              alphahull: 0, // Calculates convex hull
              name: 'Feasible Polyhedron'
            },
            {
              type: 'scatter3d',
              mode: 'markers',
              x: x,
              y: y,
              z: z,
              marker: { size: 5, color: '#ef4444' },
              name: 'Vertices'
            }
          ]}
          layout={{
            width: 700,
            height: 500,
            margin: { l: 0, r: 0, b: 0, t: 0 },
            paper_bgcolor: 'transparent',
            plot_bgcolor: 'transparent',
            scene: {
              xaxis: { title: 'X1' },
              yaxis: { title: 'X2' },
              zaxis: { title: 'X3' }
            }
          }}
          config={{ responsive: true }}
        />
      </div>
      <p className="text-xs text-center text-gray-500 mt-4">
        3D Polyhedron generated by finding the intersections of constraint planes and isolating the convex hull.
      </p>
    </div>
  );
};

export default FeasibleRegion3D;
